salary_plan:
  allocations:
  - category: Logement
    sub_allocations: null
    sub_distribution_mode: equal
    type: percent
    value: 40
  - category: Alimentation
    sub_allocations: null
    sub_distribution_mode: equal
    type: percent
    value: 20
  - category: Loisirs
    sub_allocations: null
    sub_distribution_mode: equal
    type: percent
    value: 15
  - category: Autre
    sub_allocations: null
    sub_distribution_mode: equal
    type: percent
    value: 5
  default_remainder_category: Épargne
  is_active: true
  name: Plan Standard (Recommandé)
  reference_salary: 50
