salary_plan:
  allocations:
  - category: Alimentation
    sub_allocations: null
    sub_distribution_mode: equal
    type: percent
    value: 30
  - category: Voiture
    sub_allocations: null
    sub_distribution_mode: equal
    type: percent
    value: 30
  - category: Logement
    sub_allocations: null
    sub_distribution_mode: equal
    type: percent
    value: 30
  default_remainder_category: Épargne
  is_active: false
  name: Plan par défaut
  reference_salary: 3000
