salary_plan:
  allocations:
  - category: Besoins
    sub_allocations: null
    sub_distribution_mode: equal
    type: percent
    value: 50
  - category: Loisirs
    sub_allocations: null
    sub_distribution_mode: equal
    type: percent
    value: 20
  default_remainder_category: Épargne
  is_active: true
  name: Plan Test
  reference_salary: 3000.0
